name: Smart Daily Update

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate random commit message
        id: msg
        run: |
          messages=(
            "chore: update learning progress"
            "docs: update notes"
            "feat: improve flutter practice"
            "chore: daily coding log"
            "refactor: clean code structure"
          )
          echo "msg=${messages[$RANDOM % ${#messages[@]}]}" >> $GITHUB_OUTPUT

      - name: Force file change (WAJIB biar commit selalu ada)
        run: |
          echo "Update $(date +'%Y-%m-%d %H:%M:%S')" >> activity_log.txt

      - name: Commit & Push
        run: |
          git config --global user.name "Putsaa"
          git config --global user.email "putrabtm055@gmail.com"

          git add .
          git commit -m "${{ steps.msg.outputs.msg }}"
          git push
